name: fiapx

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: fiapx
      POSTGRES_PASSWORD: fiapx
      POSTGRES_USER: fiapx
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U fiapx -d fiapx']
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  firebase-auth:
    build:
      context: .
      dockerfile: apps/firebase-emulator/Dockerfile
    image: fiapx-firebase-auth:local
    init: true
    ports:
      - '127.0.0.1:${FIREBASE_AUTH_HOST_PORT:-9099}:9099'
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    image: fiapx-api:local
    init: true
    environment:
      NODE_ENV: development
      APP_PORT: 3000
      DATABASE_URL: postgresql://fiapx:fiapx@postgres:5432/fiapx
      FIREBASE_AUTH_EMULATOR_HOST: firebase-auth:9099
      FIREBASE_PROJECT_ID: demo-fiapx
    depends_on:
      firebase-auth:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - '127.0.0.1:${API_HOST_PORT:-3000}:3000'
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

volumes:
  postgres_data:
    name: fiapx-postgres-data
