export const DATA_SOURCE = 'DATA_SOURCE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PASSWORD_HASHER = 'PASSWORD_HASHER';
export const TOKEN_ISSUER = 'TOKEN_ISSUER';
export const ID_GENERATOR = 'ID_GENERATOR';

export const VIDEO_REPOSITORY = 'VIDEO_REPOSITORY';
export const VIDEO_STORAGE = 'VIDEO_STORAGE';
export const MESSAGE_PUBLISHER = 'MESSAGE_PUBLISHER';
export const SIGNED_URL_GENERATOR = 'SIGNED_URL_GENERATOR';
export const VIDEO_CONTENT_INSPECTOR = 'VIDEO_CONTENT_INSPECTOR';
export const VIDEO_ID_GENERATOR = 'VIDEO_ID_GENERATOR';
