apiVersion: v1
kind: ConfigMap
metadata:
  name: fiapx-config
data:
  NODE_ENV: production
  PORT: '3000'
  REDIS_URL: redis://redis:6379
  S3_ENDPOINT: http://minio:9000
  S3_PUBLIC_ENDPOINT: http://localhost:9000
  S3_BUCKET: fiapx
  S3_REGION: us-east-1
  SMTP_HOST: mailhog
  SMTP_PORT: '1025'
  MAX_VIDEO_SIZE_BYTES: '524288000'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: fiapx-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: fiapx-config
            - secretRef:
                name: fiapx-secrets
          startupProbe:
            httpGet:
              path: /health/live
              port: 3000
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
            periodSeconds: 10
          resources:
            requests: { cpu: 150m, memory: 640Mi }
            limits: { cpu: '1', memory: 1536Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector: { app: api }
  ports:
    - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: worker
          image: fiapx-worker:local
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: fiapx-config
            - secretRef:
                name: fiapx-secrets
          resources:
            requests: { cpu: 300m, memory: 512Mi }
            limits: { cpu: '2', memory: 4Gi }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: fiapx-web:local
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
          resources:
            requests: { cpu: 25m, memory: 32Mi }
            limits: { cpu: 250m, memory: 128Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector: { app: web }
  ports:
    - port: 80
